# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "shaoyc9"
repo_name: "robotics-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 100

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Manipulation":
        filters: ["Robot Manipulation", "Robotic Manipulation", "Robot Learning", "Imitation Learning"]
    "VLA":
        filters: ["Vision Language Action","Vision-Language-Action"]
    "RL":
        filters: ["Robot Reinforcement Learning", "Robotic Reinforcement Learning"]
    "Tactile":
        filters: ["Tactile Sensing", "Tactile Sensing", "Tactile Perception", "Tactile Perception"]
    "Optimization":
        filters: [""]
